<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC5HJ40d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC5HJ40d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC5HJ40d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC5HJ40d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC5HJ40d\App_KernelDevDebugContainer([
    'container.build_hash' => 'C5HJ40d',
    'container.build_id' => '9823b153',
    'container.build_time' => 1683306738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC5HJ40d');
